# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenerateGoEmbed4assets < Formula
  desc "Generate go embed files for assets (.json,.yaml,.yml,...)."
  homepage "https://github.com/f9n/generate-go-embed4assets"
  version "0.1.0"
  license "GNU General Public License v3.0"

  on_macos do
    url "https://github.com/f9n/generate-go-embed4assets/releases/download/v0.1.0/generate-go-embed4assets_Darwin_all.tar.gz"
    sha256 "8dd4737c757a9ff1153338b8758529f9b22ee6ee9168704f645247e629e8a3e4"

    def install
      bin.install "generate-go-embed4assets"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/f9n/generate-go-embed4assets/releases/download/v0.1.0/generate-go-embed4assets_Linux_arm64.tar.gz"
      sha256 "1e2a886c1d4bb933b3d96d7d1abd86659b3dd1e0c1d9118a26f0ac5041ed3656"

      def install
        bin.install "generate-go-embed4assets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/f9n/generate-go-embed4assets/releases/download/v0.1.0/generate-go-embed4assets_Linux_x86_64.tar.gz"
      sha256 "e4a68f79360cd571b40f1dc9aa0706cd921d1d90e67669062d5a60b07ae25994"

      def install
        bin.install "generate-go-embed4assets"
      end
    end
  end
end
